image: Visual Studio 2017

install:
  - set QTDIR=C:\Qt\5.12\msvc2017_64
  - set PATH=%PATH%;%QTDIR%\bin;C:\Qt\Tools\QtCreator\bin
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - choco install gitversion.portable -y

build_script:
  - cmake -A x64 -B build
  - cmake --build build --config Release
  - cmake --install build --prefix appdir

after_build:
  - mkdir deploy
  - copy appdir\bin\e2designer.exe deploy\e2designer.exe
  - windeployqt --release deploy/e2designer.exe
  - ps: |
      $version = git describe
      Update-AppveyorBuild -Version ${version}
      7z a e2designer_${version}_win.zip .\deploy\*

artifacts:
  - path: "*.zip"

deploy:
  - provider: BinTray
    username: technic
    api_key:
      secure: jy1FUyYxHh37QsyYOVcrEHNNZLU/T9FFoWwiO4TVcUSfQ4zGu66G/dwxbwSqutfr
    subject: technic
    repo: e2designer
    package: e2designer
    on:
      branch: master
      # appveyor_repo_tag: true
