image: registry.gitlab.com/technic93/e2designer:latest

# To run tests with local image use
# gitlab-runner exec docker --docker-pull-policy="if-not-present" --docker-privileged <command>

variables:
  UBUNTU_IMAGE: registry.gitlab.com/technic93/e2designer:latest
  FLATPAK_IMAGE: registry.gitlab.com/technic93/e2designer:flatpak
  BINTRAY_USER: technic
  BINTRAY_REPO: e2designer
  BINTRAY_PACKAGE: e2designer
  BINTRAY_URL: https://api.bintray.com/content/technic/e2designer/e2designer
  APP_NAME: io.github.technic.e2designer
  CODE_CHECKER_VER: v6.11.1
  CLAZY_VER: "1.6"

stages:
  - images
  - build
  - tasks
  - deploy

.docker:
  stage: images
  image: docker:git
  services:
    - docker:dind
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

image:qt:
  extends: .docker
  script:
    - docker build docker/qt --pull -t $UBUNTU_IMAGE
    - docker push $UBUNTU_IMAGE
  only:
    changes:
      - docker/qt/**/*

image:flatpak:
  extends: .docker
  script:
    - docker build docker/flatpak --pull -t $FLATPAK_IMAGE
    - docker push $FLATPAK_IMAGE
  only:
    changes:
      - docker/flatpak/**/*

format:
  stage: build
  before_script:
    - clang-format --version
  script:
    - clang-format -style=file -i
      $(find . \( -path './Qt-Color-Widgets' -o -path './AppImageUpdaterBridge' \) -prune -o
      \( -name '*.hpp' -o -name '*.cpp' \) -print)
    - git diff --exit-code

before_script:
  - . /opt/qt${Qt}/bin/qt${Qt}-env.sh
  - which qmake
  - qmake --version
  - g++ --version
  - clang++ --version
  - mkdir -p ccache
  - export CCACHE_BASEDIR=${PWD}
  - export CCACHE_DIR=${PWD}/ccache
  - ccache -sz
  - export VERSION=$(git describe)
  - cat /proc/cpuinfo

build:release:
  stage: build
  script:
    - mkdir -p build && pushd build
    - qmake .. "QMAKE_CXX = ccache g++"
    - make -j$(nproc)
    - make -C app INSTALL_ROOT=$(pwd)/appdir install
    - ccache -s
  artifacts:
    paths:
      - build/
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - ccache/

build:debug:
  stage: build
  script:
    - mkdir -p build && pushd build
    - qmake .. "QMAKE_CXX = ccache g++" "CONFIG += debug"
      "QMAKE_CXXFLAGS += -fprofile-arcs -ftest-coverage" "QMAKE_LFLAGS += --coverage"
    - make -j$(nproc)
    - ccache -s
  artifacts:
    paths:
      - build/
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - ccache/

build:cmake:
  stage: build
  script:
    - mkdir -p build && pushd build
    - cmake ..
    - cmake --build .
    - QT_QPA_PLATFORM=offscreen ctest

build:clang:
  stage: build
  script:
    - mkdir -p build && pushd build
    - qmake -spec linux-clang .. "QMAKE_CXXFLAGS += -fcolor-diagnostics"
    - bear make -j$(nproc)
    - sed -e 's/"c++ /"clang++ /' -i compile_commands.json
    - ccache -s
  artifacts:
    paths:
      - build/
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - ccache/

CodeChecker:
  stage: tasks
  needs:
    - job: build:clang
      artifacts: true
  script:
    - apt-get update && apt-get install -y build-essential gcc-multilib python-virtualenv python-dev thrift-compiler
    - git clone https://github.com/Ericsson/CodeChecker.git -b "$CODE_CHECKER_VER" --depth 1 ~/codechecker
    - cd ~/codechecker && make venv && source "$PWD/venv/bin/activate"
    - make package && export PATH="$PWD/build/CodeChecker/bin:$PATH"
    - cd "$CI_PROJECT_DIR" && pushd build
    - CodeChecker analyze compile_commands.json -o ./reports
    - CodeChecker parse ./reports -e html -o ../reports_html
  artifacts:
    paths:
      - reports_html/

AppImage:
  stage: tasks
  needs:
    - job: build:release
      artifacts: true
  script:
    - pushd build
    - find appdir
    - curl -fsSL -o linuxdeployqt https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
    - chmod a+x linuxdeployqt
    - curl -fsSL -o appimagetool https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
    - chmod a+x appimagetool
    - ./linuxdeployqt appdir/usr/share/applications/e2designer.desktop -bundle-non-qt-libs
      -extra-plugins=iconengines,imageformats
    - ./appimagetool -n --bintray-user $BINTRAY_USER --bintray-repo $BINTRAY_REPO -v appdir
  artifacts:
    paths:
      - build/*.AppImage
      - build/*.AppImage.zsync

clazy:
  stage: tasks
  needs:
    - job: build:clang
      artifacts: true
  script:
    - curl -L -o /usr/local/bin/clazy "https://downloads.kdab.com/clazy/$CLAZY_VER/Clazy-x86_64-$CLAZY_VER.AppImage"
    - chmod a+x /usr/local/bin/clazy
    - pushd build
    - export CLAZY_IGNORE_DIRS="/opt/qt${Qt}|.*/Qt-Color-Widgets"
    - find .. -name '*.hpp' -o -name '*.cpp' | xargs clazy --standalone -p compile_commands.json
  when: manual

PVS-Studio:
  stage: tasks
  needs:
    - job: build:clang
      artifacts: true
  script:
    - pushd build
    - pvs-studio-analyzer credentials $PVS_NAME $PVS_KEY
    - pvs-studio-analyzer analyze -o PVS-Studio.log
    - plog-converter -t fullhtml PVS-Studio.log -o ../PVS-Studio.html
  artifacts:
    paths:
      - PVS-Studio.html

test:
  stage: tasks
  needs:
    - job: build:release
      artifacts: true
  script:
    - pushd build
    - QT_QPA_PLATFORM=offscreen make check

coverage:
  stage: tasks
  needs:
    - job: build:debug
      artifacts: true
  script:
    - pushd build
    - QT_QPA_PLATFORM=offscreen make check
    - popd
    - lcov --no-external --directory . --capture --output-file coverage.info
    - lcov --remove coverage.info "moc_*" "*.moc" "qrc_*" "tests/*" --output-file coverage.info
    - lcov --list coverage.info
    - genhtml coverage.info --output-directory coverage-report
    - bash <(curl -s https://codecov.io/bash) -f coverage.info
  coverage: '/Total:\|(\d+\.?\d+\%)/'
  artifacts:
    paths:
      - coverage-report/

flatpak:
  image: $FLATPAK_IMAGE
  stage: build
  before_script:
    - flatpak --version
    - flatpak-builder --version
  script:
    - flatpak run org.freedesktop.appstream-glib validate misc/e2designer.appdata.xml
    - desktop-file-validate misc/e2designer.desktop
    - cat $APP_NAME.yaml | yaml2json.py > $APP_NAME.json
    - flatpak-builder --ccache --repo=flatpak-repo flatpak-build $APP_NAME.json
    - flatpak-builder --env=QT_QPA_PLATFORM=offscreen --run flatpak-build $APP_NAME.json e2designer -h
    - flatpak build-bundle flatpak-repo e2designer.flatpak $APP_NAME
  artifacts:
    paths:
      - "*.flatpak"

deploy:
  stage: deploy
  only:
    - master
  needs:
    - job: AppImage
      artifacts: true
    - job: flatpak
      artifacts: true
    - test
    - coverage
  script:
    - curl -T build/e2designer-$VERSION-x86_64.AppImage -u technic:$BINTRAY_API_KEY
      $BINTRAY_URL/$VERSION/e2designer-$VERSION-x86_64.AppImage
    - curl -T build/e2designer-$VERSION-x86_64.AppImage.zsync -u technic:$BINTRAY_API_KEY
      $BINTRAY_URL/$VERSION/e2designer-$VERSION-x86_64.AppImage.zsync
    - curl -T e2designer.flatpak -u technic:$BINTRAY_API_KEY
      $BINTRAY_URL/$VERSION/e2designer-$VERSION.flatpak
    - python3 bintray.py
