name: Flatpak

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-5.15
      options: --privileged
    
    steps:
    - uses: actions/checkout@v2
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      with:
        manifest-path: io.github.technic.e2designer.yaml
        cache-key: flatpak-builder-${{ github.sha }}

    - uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: app.flatpak
        asset_name: e2designer-$tag.flatpak
        tag: latest
        overwrite: true
        prerelease: true
        body: "Latest build from master"
