name: build

on:
  push:
    branches: [master]

jobs:
  build_mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get git log
        run: |
          git fetch --unshallow --tags
          git describe
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.12
      - name: Build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build
      - name: Test
        run: |
          cmake --build build --target test
      - name: Generate Icons
        run: ./mkicns.sh misc/e2designer.png appdir/icons.icns
      - name: Package
        run: cmake --build build --target package
      - uses: actions/upload-artifact@v1
        with:
          name: macos installer
          path: build/bin/e2designer.dmg
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/bin/e2designer.dmg
          asset_name: macOS app
          tag: ${{ github.ref }}
          overwrite: true
          body: "Latest build from master"
