name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_mac:
    runs-on: macos-latest

    env:
      BINTRAY_URL: https://api.bintray.com/content/technic/e2designer/e2designer
      BINTRAY_API_KEY: ${{secrets.BINTRAY_API_KEY}}

    steps:
      - uses: actions/checkout@v2
      - name: Get git log
        run: |
          git fetch --unshallow --tags
          git describe
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
      - name: Build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build
      - name: Test
        run: |
          cmake --build build --target test
      - name: Package
        run: |
          mkdir appdir
          ./mkicns.sh misc/e2designer.png appdir/icons.icns
          cmake --install build --prefix appdir --component application
          macdeployqt appdir/bin/e2designer.app -verbose=2 -dmg 
          find appdir
      - uses: actions/upload-artifact@v1
        with:
          name: macos installer
          path: appdir/bin/e2designer.dmg
      - name: Deploy to bintray
        run: |
          export VERSION=$(git describe)
          curl -T app/e2designer.dmg -u "technic:$BINTRAY_API_KEY" "$BINTRAY_URL/$VERSION/e2designer-$VERSION.dmg"
